// import Icons 
import 'bootstrap-icons/font/bootstrap-icons.css'; 
// import bootstrap 
import 'bootstrap/dist/css/bootstrap.css'; 
// import aos css 
import 'aos/dist/aos.css';
import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import Header from '@/components/Header';
import "./variables.css";
import "./globals.css";

const OSwald = Oswald({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "News Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OSwald.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
